# Generated by Django 5.2.6 on 2025-09-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField(max_length=100)),
                ('project_description', models.TextField()),
                ('project_timestamp', models.DateTimeField(auto_now_add=True)),
                ('project_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
