# Generated by Django 5.2.6 on 2025-09-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('Phone_number', models.CharField(max_length=10)),
                ('prefered_date', models.DateField(auto_now_add=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
