# Generated by Django 5.2.6 on 2025-09-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='email',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='Phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
