# Generated by Django 5.2.6 on 2025-09-13 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_bookings_email_alter_bookings_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='firstname',
            new_name='name',
        ),
    ]
